name: Documentation-CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

# Prevent multiple builds of this workfkow from running at the same time and allow cancelation of builds in progress.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
    # add job to build, configure and test doxygen documentation
    build_and_test:
      runs-on: ubuntu-22.04
      timeout-minutes: 120
      steps:
        # add Checkout step to fetch the repository with submodules
        - name: Checkout
          uses: actions/checkout@v2
          with:
            submodules: recursive

        # add Install Cmake step to install cmake from seqan/actions/setup-cmake
        - name: Install CMake
          uses: seqan/actions/setup-cmake@main
          with:
            cmake: 3.27.4

        # add Install latex step to install latex from ubuntu package manager
        - name: Install Latex
          run: |
            sudo apt-get update
            sudo apt-get install texlive texlive-font-utils -y

        # add Install Doxygen step to install doxygen from seqan/actions/setup-doxygen
        - name: Install Doxygen
          uses: seqan/actions/setup-doxygen@main
          with:
            doxygen: 1.9.6

        # Install python 3.11
        - name: Set up Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: 3.11

        # Install sphinx, breathe, furo, and exhale into virtual environment
        - name: Run Python commands
          run: |
            pip install --upgrade pip
            pip install -r doc/requirements.txt
            sphinx-build --version

        # add Build Tests step to configure and build documentation tests
        - name: Build Tests
          run: |
            mkdir -p build
            cd build
            cmake ..
            make docs_sphinx

        # add Run Tests step to run documentation tests using 2 threads in current directory with outputting on failure
        - name: Run Tests
          run: |
            cd build
            ctest --output-on-failure --test-dir doc

        - name: Upload documentation
          uses: actions/upload-artifact@v2
          with:
            name: docs
            path: |
              build/doc/build
              !build/doc/build/html
              !build/doc/build/xml
              !build/doc/build/Doxyfile
              !build/doc/build/_sources
              !build/doc/build/latex

    deploy:
      permissions:
        contents: read
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build_and_test
      steps:
        - name: Download documentation
          uses: actions/download-artifact@v3
          with:
            name: docs
        - name: Setup Pages
          uses: actions/configure-pages@v3
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2
          with:
            # Upload build directory as artifact
            path: '.'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2

