name: Documentation-CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

# Prevent multiple builds of this workfkow from running at the same time and allow cancelation of builds in progress.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
    run:
      uses: ./.github/workflows/build_and_test_docs.yml
      with:
        os: ubuntu-latest
