name: libjst-CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  # add test matrix to run tests on ubuntu-22.04 and macos-12 using g++12
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        compiler: [gcc-12]
        build_type: [Release]
        test_suite: ["test/api/libjst"]
        cxx_flags: ["-fdiagnostics-color -ftemplate-backtrace-limit=0 -fconcepts-diagnostics-depth=2"]
        include:
          - os: macos-12
            threads: 3
          - os: ubuntu-22.04
            threads: 2

    runs-on: ${{ matrix.os }}
    steps:
      # add Checkout step to fetch repository with recursive submodules
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # add Setup toolchain for tests
      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 75M

      # add Install cmake step to install cmake 3.27.4 from seqan/actions main
      - name: Install cmake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.27.4

      # add Build Tests step to configure and build documentation tests
      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }} \
                   -DCMAKE_CXX_FLAGS:STRING="${{ matrix.cxx_flags }}"
      - name: Build
        run: |
          ccache -z
          cd build/${{ matrix.test_suite }}
          make -k -j${{ matrix.threads }}
          ccache -sv

      - name: Test
        run: |
          cd build/${{ matrix.test_suite }}
          ctest . -j${{ matrix.threads }} --output-on-failure
